[package]
name = "st-rust"
version = "0.1.0"
authors = ["Antoine Busch <antoine.busch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="0.3.5", features=["full"]}
anyhow = "1.0.37"
bytes = "1.0.0"
byteorder = "1.3.4"
